### ISSUE TITLE
Failing to Load

### ISSUE THREAD

**Issue by Dystinct** [StacheSebastian/CreateArmoredCopperBacktanks#1]
Forge | forge 40.1.73
Create | create-1.18.2-0.5.0.d
Flywheel | flywheel-forge-1.18.2-0.6.5
CreateArmoredCopperBacktanks | createab-1.18.2-5.0.7.1

[crash-2022-08-17_13.23.37-fml.txt](https://github.com/StacheGamer1609/CreateArmoredCopperBacktanks/files/9365334/crash-2022-08-17_13.23.37-fml.txt)

Without reading into it, possibly some kind of Compat issue, as there is another mod also giving the same issue.
https://github.com/talrey/CreateDeco/issues/36

**Comment by StacheSebastian** [comment]
Thank you for the report.
Most Create Addons probably have this problem or at least every Addon that is using Create's Registration Helper. They changed it, so the mods aren't compatible with the newest version.

**Comment by Dystinct** [comment]
Well that is a bummer, but thanks for letting me know as quickly as you did! As I am nearly on Day 8 of a separate mod issue, with NO contact at all. But after reading some other bug reports it doesn't seem like this is an uncommon occurrence, sadly.

Now I feel kinda bad, yet relived that the first issue with this mod is something that was caused by something outside of the mod itself rather than a misplaced character or symbol.

**Comment by StacheSebastian** [comment]
I'll fix the issue soon, and I wish you good luck and success with your other Issues.

**Comment by Sshmoob** [comment]
Hey, how long until this gets fixed? I want to update my modpack to Create 0.5d but your mod still doesn't work with it yet.
